server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/antd_pro
    username: root
    password: jiangdawei56632
  redis:
    host: 192.168.56.10
    port: 6379
  jackson:
    date-format: yyyy-MM-dd

oss:
  accessKeyId: xxx
  accessKeySecret: xxx
  endpoint: xxx
  bucketName: xxx
