server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/antd_pro
    username: root
    password: jiangdawei56632
  redis:
    host: 192.168.56.3
    port: 6379
  jackson:
    date-format: yyyy-MM-dd

oss:
  accessKeyId: LTAI5tFBhHHBU6D9B4RKcBze
  accessKeySecret: 7n12l9Bycwj7aEleK12Qb1hzECaBG3
  endpoint: oss-cn-hangzhou.aliyuncs.com
  bucketName: edu-56632